spring:
  datasource:
    driver-class-name: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.106.123.27:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
server:



